```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(here)
```

```{r}
annotation_table = read_tsv(here("data/signatures/202506_TB_signatures_info.tsv"))
```

```{r}
sorted_annotation_table <- annotation_table %>%
  arrange(
    desc(technology),
    tissue_category,
    sample_origin,
    tissue_cell_type,
    series_id,
    tb_status,
    desc(disease_samples),
    desc(control_samples)
  )

extra_rows <- tibble::tibble(
  series_id        = c(NA_character_, NA_character_),
  SIGNATURE_NAME   = c("microarray_aggregated_signature",
                       "RNAseq_aggregated_signature"),
  tb_status        = c(NA_character_, NA_character_),
  tissue_category  = c(NA_character_, NA_character_),
  tissue_cell_type = c(NA_character_, NA_character_),
  sample_origin    = c(NA_character_, NA_character_),
  EXPRMAT_PATH     = c(NA_character_, NA_character_),
  signature        = c(1, 1),
  up_genes_num     = c(98, 98),
  dn_genes_num     = c(98, 98),
  control_samples  = c(NA_integer_, NA_integer_),
  disease_samples  = c(NA_integer_, NA_integer_),
  technology       = c("microarray", "RNAseq")
)

sorted_annotation_table <- dplyr::bind_rows(
  sorted_annotation_table,
  extra_rows
)

sorted_annotation_table <- sorted_annotation_table %>%
  mutate(
    signature_ID = paste0("s", row_number()),
    number = row_number()
  ) %>%
  relocate(signature_ID, .before = number)

sorted_annotation_table <- sorted_annotation_table %>%
  mutate(dataset_ID = paste0("d", match(series_id, unique(series_id))))

sorted_annotation_table$dataset_signature_ID <- paste(
  sorted_annotation_table$signature_ID,
  sorted_annotation_table$dataset_ID,
  sep = "_"
)

write_tsv(sorted_annotation_table, file = here("figures/annotation_table.tsv"))

```
