```{r}
library(readr)
library(simplifyEnrichment)
library(here)
source(here("scripts/00_get_crossSigs_enrichedGO.R"))

up_zerodev = read_tsv(here("figures/up_zerodev_squareddev.tsv"))
dn_zerodev = read_tsv(here("figures/dn_zerodev_squareddev.tsv"))
annotation_file='data/metadata/direct-annotations__Homo_sapiens__Entrez.tsv'
GO_annotation = get_GO_annotation(here(annotation_file))

# map the GO descriptions to GO ids | up
GO_df_up <- merge(up_zerodev, GO_annotation, by.x="Pathway", by.y="Term", all.x=T, all.y=F)
GO_clean_up <- na.omit(GO_df_up)
GOids_terms_up <- unique(GO_clean_up[,c("GOID","Pathway")])
GOids_up <- GOids_terms_up$GOID

# map the GO descriptions to GO ids | dn
GO_df_dn <- merge(dn_zerodev, GO_annotation, by.x="Pathway", by.y="Term", all.x=T, all.y=F)
GO_clean_dn <- na.omit(GO_df_dn)
GOids_terms_dn <- unique(GO_clean_dn[,c("GOID","Pathway")])
GOids_dn <- GOids_terms_dn$GOID
  
```

```{r}
# calculate similarity matrix
simMat_up <- GO_similarity(go_id = GOids_up, ont = 'BP', db = "org.Hs.eg.db",
                          measure = "Rel",remove_orphan_terms = FALSE) # “Wang”, “Resnik”, “Rel”, “Jiang”, “Lin”, “TCSS”

simMat_dn <- GO_similarity(go_id = GOids_dn, ont = 'BP', db = "org.Hs.eg.db",
                          measure = "Rel",remove_orphan_terms = FALSE) # “Wang”, “Resnik”, “Rel”, “Jiang”, “Lin”, “TCSS”
```

```{r}
simMat_up_ = simMat_up
simMat_up_[simMat_up_ < 0.6] <- 0

pdf(here("figures/FigureSX_up_squared_deviation_well_captured.pdf"),
    width = 30, height = 30)  
simplifyGO(simMat_up_)
dev.off()

```

```{r}
simMat_dn_ = simMat_dn
simMat_dn_[simMat_dn_ < 0.6] <- 0

pdf(here("figures/FigureSX_dn_squared_deviation_well_captured.pdf"),
    width = 30, height = 30)  
simplifyGO(simMat_dn_)
dev.off()
```