# Sanity check on sample sizes of each signature
# Criteria: each signature must have at least 3 disease and 3 control expression samples
# Last modified: 11/04/25
# Author: Kewalin Samart

```{r}
library(here)
library(readr)
library(tidyverse)
```

```{r microarray signatures}
microarray_annotation = read_tsv(here("data/microarray_data_forDE/clean_TB_sample_metadata_classification.tsv"))

marray_sample_counts <- microarray_annotation %>%
  group_by(SIGNATURE_NAME) %>%
  summarise(
    disease = sum(CLASSIFICATION == "disease without treatment"),
    control = sum(CLASSIFICATION == "healthy control without treatment"),
    .groups = "drop"
  )

write_tsv(marray_sample_counts, here("data/microarray_data_forDE/clean_microarray_sample_sizes.tsv"))
```

```{r RNAseq sugnatures}
rnaseq_annotation = read_tsv(here("data/RNAseq_data_forDE/clean_TB_sample_metadata_classification.tsv"))

rnaseq_sample_counts <- rnaseq_annotation %>%
  group_by(SIGNATURE_NAME) %>%
  summarise(
    disease = sum(CLASSIFICATION == "disease without treatment"),
    control = sum(CLASSIFICATION == "healthy control without treatment"),
    .groups = "drop"
  )

write_tsv(rnaseq_sample_counts, here("data/RNASeq_data_forDE/clean_RNAseq_sample_sizes.tsv"))
```