# Functions to summarize drug results prioritized by multiple methods
## 1. method-wise summarization

```{r sourcing function script}
library(readr)
library(here)
source(here("scripts/03_summarize_drugs_methodswise_functions.R"))
```

```{r get_drug_results WCS}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "LINCS"
drug_res_path = "results/microarray/LINCS/"
score = "WCS"

combined_drug_df_WCS = get_drug_results(data_to_run, drug_res_path, score_method, score)
WCS_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_WCS, score, stats = "median")
score_vec_WCS <- as.numeric(unlist(combined_drug_df_WCS[1]))
threshold <- determine_threshold(score_vec_WCS, values = "neg", tail = "left", score_percentile=0.9)
pert_occurrence_WCS <- get_reversing_drugs_freq(WCS_combined_drug_df, threshold=threshold, values="neg")
```

```{r get_drug_results NCS}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "LINCS"
drug_res_path = "results/microarray/LINCS/"
score = "NCS"

combined_drug_df_NCS = get_drug_results(data_to_run, drug_res_path, score_method, score)
NCS_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_NCS, score, stats = "median")
score_vec_NCS <- as.numeric(unlist(combined_drug_df_NCS[1]))
threshold <- determine_threshold(score_vec_NCS, values = "neg", tail = "left", score_percentile=0.9)
pert_occurrence_NCS <- get_reversing_drugs_freq(NCS_combined_drug_df, threshold=threshold, values="neg")
```

```{r get_drug_results Tau}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "LINCS"
drug_res_path = "results/microarray/LINCS/"
score = "Tau"

combined_drug_df_Tau = get_drug_results(data_to_run, drug_res_path, score_method, score)
Tau_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_Tau, score, stats = "median")
```

```{r get_drug_results CMAP}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "CMAP"
drug_res_path = "results/microarray/CMAP/"
score = "CMAP"

combined_drug_df_CMAP = get_drug_results(data_to_run, drug_res_path, score_method, score)
CMAP_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_CMAP, score, stats = "median")
```

```{r get_drug_results Cor_pearson}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "Cor_pearson"
drug_res_path = "results/microarray/Cor_pearson/"
score = "Cor_pearson"

combined_drug_df_pearson = get_drug_results(data_to_run, drug_res_path, score_method, score)
pearson_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_pearson, score, stats = "median")
```

```{r get_drug_results Cor_spearman}
# read in data_to_run df
microarray_data_to_run = read_tsv(here("data/v2/signatures/microarray_TB_signature_run_info.tsv"))
data_to_run = microarray_data_to_run[microarray_data_to_run$signature == 1,]
score_method = "Cor_spearman"
drug_res_path = "results/microarray/Cor_spearman/"
score = "Cor_spearman"

combined_drug_df_spearman = get_drug_results(data_to_run, drug_res_path, score_method, score)
spearman_combined_drug_df = get_DrugDis_ScoreMatrix(combined_drug_df_pearson, score, stats = "median")
```


