# Compute aggregated signatures from individual DE signatures for pathway analyses

##### Load libraries and sort scripts
```{r}
library(readr)
library(here)
source(here("scripts/00_background_genes_PA_functions.R"))
source(here("scripts/01_signature_aggregation_functions.R"))
```

### Getting up/dn microarray/RNAseq DE signatures
```{r}
# set up parameters
technologies = c("microarray", "RNAseq")
directions = c("up","dn")
bg_source = "input data" # all genes across datasets
threshold_pct <- c(0.95,0.9,0.85,0.8,0.75,0.7,0.65,0.6,0)

for(threshold in threshold_pct){
  for(technology in technologies){
    for(direction in directions){
      # set up paths
      metadata_path = here(paste0("data/signatures/",technology,"_TB_signature_run_info.tsv"))
      data_path = here(paste0("data/DE_results/",technology))
      output_dir = here(paste0("data/DE_results/",technology,"/aggregated_DE_signatures_sensitivity"))
      extension = paste0("_",direction,".tsv")
      
      # get gene membership matrix and save it
      gene_membership_matrix = compute_membership_matrix(metadata_path = metadata_path, data_path = data_path, 
                            direction = direction, bg_source = bg_source, 
                            lincs_genetype = NULL, output_dir = output_dir, extension = extension, save_result=TRUE)
      
      # get jaccard matrix and save it
      jaccard_matrix = compute_jaccard_matrix(metadata_path = metadata_path, data_path = data_path, 
                         direction = direction, output_dir = output_dir, save_result=TRUE) 
      
      # compute aggregates signature and save it
      aggregate_signatures(gene_membership_matrix, jaccard_matrix, output_dir, direction, threshold_pct = threshold, save_result=TRUE)
    }
  }
}
```
