# Combine enrichment across individual signatures and aggregated signatures of different aggregation thresholds (downregulated)

```{r setup, include=FALSE}
library(ComplexHeatmap)
library(clusterProfiler)
library(GOSemSim)
library(org.Hs.eg.db)
library(circlize)
library(grid)
library(tidyverse)
library(here)
source(here("scripts/00_get_crossSigs_enrichedGO.R"))
```

```{r read in metadata tabel}
summary_df <- read.delim(here("figures/figure2/metadata_annotation/annotation_table.tsv"), sep = "\t", stringsAsFactors = FALSE)
```

```{r define indiv file paths}
marray_path_dn <- here("data/microarray_pathways/dn")
rnaseq_path_dn <- here("data/RNAseq_pathways/dn")
```

```{r define accessory variables/paths}
pattern <- "allterms_GO_ORA_BGcorrected"
prefix_sub <- "allterms_GO_ORA_BGcorrected"
suffix_sub <- "dn.tsv"
annotation_file='data/metadata/direct-annotations__Homo_sapiens__Entrez.tsv'
```

```{r annotation}
GO_annotation = get_GO_annotation(here(annotation_file))
```

```{r microarray and RNAseq up pathways}
# get asinh matrix with all available pathways
marray_GO_mat_dn = get_GO_asinh_matrix(marray_path_dn, pattern, prefix_sub, suffix_sub)
rnaseq_GO_mat_dn = get_GO_asinh_matrix(rnaseq_path_dn, pattern, prefix_sub, suffix_sub)
```

```{r process all terms matrices}
# aggregated thresholds
agg_cols <- c(
  "dn_aggregated_signature_0",
  "dn_aggregated_signature_0.6",
  "dn_aggregated_signature_0.75",
  "dn_aggregated_signature_0.7",
  "dn_aggregated_signature_0.75",
  "dn_aggregated_signature_0.8",
  "dn_aggregated_signature_0.85",
  "dn_aggregated_signature_0.9",
  "dn_aggregated_signature_0.95"
)

# microarray
cols_to_keep_marray <- intersect(
  colnames(marray_GO_mat_dn),
  c("Description", summary_df$signature_name, agg_cols)
)

df1 <- marray_GO_mat_dn[, cols_to_keep_marray]

colnames(df1) <- gsub(
  "dn_aggregated_signature_",
  "dn_aggregated_microarray_",
  colnames(df1)
)

colnames(df1) <- gsub("^dn_", "", colnames(df1))


# RNAseq
cols_to_keep_rnaseq <- intersect(
  colnames(rnaseq_GO_mat_dn),
  c("Description", summary_df$signature_name, agg_cols)
)

df2 <- rnaseq_GO_mat_dn[, cols_to_keep_rnaseq]

colnames(df2) <- gsub(
  "dn_aggregated_signature_",
  "dn_aggregated_RNAseq_",
  colnames(df2)
)

colnames(df2) <- gsub("^dn_", "", colnames(df2))

# reshape from wide to long
long1 <- pivot_longer(df1, -Description, names_to = "Signature", values_to = "Value")
long2 <- pivot_longer(df2, -Description, names_to = "Signature", values_to = "Value")

# combine long formats and sum values where matching
combined_long <- bind_rows(long1, long2) %>%
  group_by(Description, Signature) %>%
  summarise(
  Value = if (all(is.na(Value))) NA_real_ else max(Value, na.rm = TRUE),
  .groups = "drop"
)

# reshape back to wide format
final_df_dn <- pivot_wider(combined_long, names_from = Signature, values_from = Value)
colnames(final_df_dn) <- gsub("\\.", "-", colnames(final_df_dn))

# identify columns with "aggregated" in their names
agg_cols <- grep("aggregated", names(final_df_dn), value = TRUE)

# identify columns that do not contain "aggregated"
non_agg_cols <- setdiff(names(final_df_dn), agg_cols)

# reorder the dataframe
final_df_dn <- final_df_dn[, c(non_agg_cols, agg_cols)]

# identify columns
desc_col <- grep("Description", names(final_df_dn), value = TRUE)
gpl_cols <- grep("GPL", names(final_df_dn), value = TRUE)
rnaseq_col <- grep("RNAseq", names(final_df_dn), value = TRUE)
other_cols <- setdiff(names(final_df_dn), c(gpl_cols, rnaseq_col))

# reorder dataframe
final_df_dn <- final_df_dn[, c(desc_col, gpl_cols, other_cols, rnaseq_col)]
final_df_dn <- final_df_dn[, !duplicated(colnames(final_df_dn))]
final_df_dn <- final_df_dn[, !grepl("HIV", colnames(final_df_dn))]
write_tsv(final_df_dn, here("figures/figureS4/figureS4b/marray_rnaseq_asinh_dn_pathways_sensitivity.tsv"))
```