# Obtain node and edge data for figure 3: disease-drug-target network
### last modified: 07/15/25
### Author: Kewalin Samart

```{r load libraries and functions}
library(readr)
library(here)
source(here("scripts/05_build_drugtarget_network_functions.R"))
```

```{r get disease genes}
microarray_up_aggr_genes = as.character(read_tsv(here("data/v2/figure3/microarray_up_aggregated_signature.tsv"), show_col_types = FALSE)$GeneID)
microarray_dn_aggr_genes = as.character(read_tsv(here("data/v2/figure3/microarray_dn_aggregated_signature.tsv"), show_col_types = FALSE)$GeneID)

rnaseq_up_aggr_genes = as.character(read_tsv(here("data/v2/figure3/RNAseq_up_aggregated_signature.tsv"), show_col_types = FALSE)$GeneID)
rnaseq_dn_aggr_genes = as.character(read_tsv(here("data/v2/figure3/RNAseq_dn_aggregated_signature.tsv"), show_col_types = FALSE)$GeneID)

up_aggr_genes = intersect(microarray_up_aggr_genes, rnaseq_up_aggr_genes)
dn_aggr_genes = intersect(microarray_dn_aggr_genes, rnaseq_dn_aggr_genes)

TB_aggregated_genes = unique(union(up_aggr_genes, dn_aggr_genes))

write_tsv(as.data.frame(TB_aggregated_genes), file = here("data/v2/figure3/TB_aggregated_genes.tsv"))
```

```{r get final drug list}
RAresult_indivSig_TB_RNAseq <- readRDS(here("data/v2/figure3/RAresult_indivSig_TB_RNAseq.rds"))
RAresult_indivSig_TB_microarray <- readRDS(here("data/v2/figure3/RAresult_indivSig_TB_microarray.rds"))
RAresult_aggrSig_TB_RNAseq <- readRDS(here("data/v2/figure3/RAresult_neg_left_0.9_aggrSig_TB_RNAseq.rds"))
RAresult_aggrSig_TB_microarray <- readRDS(here("data/v2/figure3/RAresult_neg_left_0.9_aggrSig_TB_microarray.rds"))

indiv_result <- union(RAresult_indivSig_TB_RNAseq, RAresult_indivSig_TB_microarray)
aggr_result <- union(RAresult_aggrSig_TB_RNAseq, RAresult_aggrSig_TB_microarray)
final_drugs <- intersect(indiv_result, aggr_result)
final_drugs 
```

```{r get drug-interacting genes}
DGIdb_targets_list = get_DTG_interactions_DGIdb(drug_names = final_drugs)
DGIdb_targets_df = get_DGIdb_targets_table(DGIdb_targets_list)
```

```{r read in drug signature matrix}
signature_matrix = read_tsv(here("data/v2/figure3/GSE92742_level5_signatures_lm.tsv"))
```

```{r read in drug signature metadata}
library(data.table)
signature_metadata <- fread(here("data/v2/figure3/GSE92742_Broad_LINCS_sig_info.txt"))
```

```{r get drug perturbed genes}
drug_genes_df <- get_drug_perturbed_genes(drug_names = final_drugs,
                         signature_matrix = signature_matrix,
                         signature_metadata = signature_metadata,
                         time_point = "24 h",
                         dosage = "10 µM",
                         N = 2,
                         gene_conversion_file = here("data/metadata/Homo_sapiens.gene_info.csv"))

```

#### Create node_types.txt for figure 3
```{r}
# read in gene mapping
gene_mapping = read_csv(here("data/metadata/Homo_sapiens.gene_info.csv"))
gene_mapping = gene_mapping[,c('GeneID','Symbol')]
TB_aggregated_genes = gene_mapping[gene_mapping$GeneID %in% TB_aggregated_genes,]$Symbol

node_TB_genes <- TB_aggregated_genes
type_TB_genes <- "source"

TB_genes_df <- data.frame(node = node_TB_genes, type = type_TB_genes, stringsAsFactors = FALSE)

node_drug_genes <- union(drug_genes_df$drug_gene, DGIdb_targets_df$target)
type_drug_genes <- "target"
drug_perturbed_genes_df <- data.frame(node = node_drug_genes, type = type_drug_genes, stringsAsFactors = FALSE)

node_type_df <- rbind(TB_genes_df, drug_perturbed_genes_df)
```

#### Create and save node/edge data for figure S3
```{r obtain node data}
node_data <- get_drugtarget_NetworkNodeData(drug_names = final_drugs,
                               drug_genes_df = drug_genes_df,
                               disease_pathways = c(),
                               N = 15,
                               interaction_file = here("data/metadata/interactions_DGIdb.tsv"),
                               intscore_values = "all",
                               intscore_tail = "right",
                               intscore_pct = 0.9,
                               moas = c())

```

```{r add STRING genes to the node data}
node_data_STRING <- add_STRING_genes(node_data,
                                    STRING_path = here("data/metadata/STRING_hs_interactions.txt"),
                                    STRING_intscore = 0.7,
                                    min_degree = 4,
                                    disease_genes = c())

```

```{r get edge data from the node data}
edge_data = get_drugtarget_NetworkEdgeData(network_nodes = node_data_STRING)

```
