```{r setup, include=FALSE}
library(ComplexHeatmap)
library(colorRamp2)
library(clusterProfiler)
library(DOSE)
library(org.Hs.eg.db)
library(readr)
library(here)
source(here("scripts/00_get_crossSigs_enrichedGO.R"))
library(gridExtra)
library(grid)
library(tibble)
library(tidyr)
library(tidyverse)
```

```{r up aggregated signatures | microarray and RNAseq} 
aggr_enrichGO_res_up_marray = read_tsv(here("data/v2/microarray_pathways/up/GO_ORA_BGcorrected_up_aggregated_microarray.tsv"))
aggr_enrichGO_res_up_rnaseq = read_tsv(here("data/v2/RNAseq_pathways/up/GO_ORA_BGcorrected_up_aggregated_RNAseq.tsv"))
```

### Up individual signatures
```{r define indiv file paths}
marray_path_up <- here("data/v2/microarray_pathways/up")
marray_path_dn <- here("data/v2/microarray_pathways/dn")
rnaseq_path_up <- here("data/v2/RNAseq_pathways/up")
rnaseq_path_dn <- here("data/v2/RNAseq_pathways/dn")
```

```{r define accessory variables/paths}
pattern <- "GO_ORA_BGcorrected"
prefix_sub <- "GO_ORA_BGcorrected"
suffix_sub <- "up.tsv"
annotation_file='data/metadata/direct-annotations__Homo_sapiens__Entrez.tsv'
```

```{r microarray up pathway clusters}
marray_GO_mat_up = get_GO_generatio_matrix(marray_path_up, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

```{r RNAseq up pathway clusters}
rnaseq_GO_mat_up = get_GO_generatio_matrix(rnaseq_path_up, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

# combine pathways from both marray and rnaseq and perform clustering
```{r read in metadata tabel}
summary_df <- read.delim(here("data/metadata/202506_TB_signatures_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
new_row_aggr <- data.frame(
  study_id = c(NA,NA),
  platform_id = c(NA,NA),
  tb_status = c(NA,NA),
  time_point = c(NA,NA),
  tissue_cell_type = c(NA,NA),
  sample_origin = c(NA,NA),
  tissue_category = c(NA,NA),  
  series_id = c(NA,NA), 
  SIGNATURE_NAME = c("aggregated_TB_signature1", "aggregated_TB_signature2"),  
  EXPRMAT_PATH = c(NA,NA),    
  signature = c(1,1),
  up_genes_num = c(98,98),
  dn_genes_num = c(98,98),
  technology = c("microarray", "RNASeq")
)

final_summary_df = rbind(summary_df, new_row_aggr)
write_tsv(final_summary_df, here("data/metadata/202506_all_TB_signatures_info.tsv"))
```


```{r}
# Assuming both data frames have Description as row names
# If it's a column instead, set it as rownames first

cols_to_keep_marray <- intersect(colnames(marray_GO_mat_up), c("Description", summary_df$SIGNATURE_NAME, "up_aggregated_microarray"))
df1 <- marray_GO_mat_up[, cols_to_keep_marray]

cols_to_keep_rnaseq <- intersect(colnames(rnaseq_GO_mat_up), c("Description", summary_df$SIGNATURE_NAME, "up_aggregated_RNAseq"))
df2 <- rnaseq_GO_mat_up[, cols_to_keep_rnaseq]

# Reshape from wide to long
library(tidyr)
long1 <- pivot_longer(df1, -Description, names_to = "Signature", values_to = "Value")
long2 <- pivot_longer(df2, -Description, names_to = "Signature", values_to = "Value")

# Combine long formats and sum values where matching
library(dplyr)
combined_long <- bind_rows(long1, long2) %>%
  group_by(Description, Signature) %>%
  summarise(Value = sum(Value, na.rm = TRUE), .groups = "drop")

# Reshape back to wide format
final_df_up <- pivot_wider(combined_long, names_from = Signature, values_from = Value)
colnames(final_df_up) <- gsub("\\.", "-", colnames(final_df_up))

# Identify columns with "aggregated" in their names
agg_cols <- grep("aggregated", names(final_df_up), value = TRUE)

# Identify columns that do not contain "aggregated"
non_agg_cols <- setdiff(names(final_df_up), agg_cols)

# Reorder the dataframe
final_df_up <- final_df_up[, c(non_agg_cols, agg_cols)]
# Identify columns
desc_col <- grep("Description", names(final_df_up), value = TRUE)
gpl_cols <- grep("GPL", names(final_df_up), value = TRUE)
rnaseq_col <- grep("RNAseq", names(final_df_up), value = TRUE)
other_cols <- setdiff(names(final_df_up), c(gpl_cols, rnaseq_col))

# Reorder dataframe
final_df_up <- final_df_up[, c(desc_col, gpl_cols, other_cols, rnaseq_col)]
```

### up pathway clusters combining aggr and indiv results
```{r}
rnaseq_marray_GO_mat_up <- final_df_up
# USE STATISCALLY SIGNIFICANT TERMS INSTEAD
# read in the df
#up_stat_terms = read_tsv("/Users/kewalinsamart/Documents/GitHub/drugrep_tb/figures/up_stats_terms_cellline_EX3521_GPL751_df.tsv")
#rnaseq_marray_GO_mat_up = final_df_up[final_df_up$Description %in% up_stat_terms$GO_term,]
# now highly viable terms instead
# count number of non-NA and non-zero entries per row (excluding Description column)
final_df_up_indiv <- final_df_up[, !grepl("aggregated", colnames(final_df_up))]

library(dplyr)

viable_counts <- final_df_up_indiv %>%
  as.data.frame() %>%
  dplyr::select(-Description) %>%
  dplyr::mutate(across(everything(), ~ as.numeric(.))) %>%
  apply(1, function(row) sum(!is.na(row) & row != 0))


# filter terms that are viable in at least N signatures (e.g., 2 or more)
N <- 18  # change this threshold as needed
final_df_up_viable <- final_df_up[viable_counts >= N, ]

#rnaseq_marray_GO_mat_up = final_df_up[final_df_up$Description %in% final_df_up_viable$Description,]
```

```{r}
row.names(final_df_up_viable) <- final_df_up_viable$Description
final_df_up_viable$Description <- NULL
sig_mat_indiv_aggr_up <- as.matrix(final_df_up_viable)
colnames(sig_mat_indiv_aggr_up) <- gsub("\\.", "-", colnames(sig_mat_indiv_aggr_up))
sig_mat_indiv_aggr_up[is.na(sig_mat_indiv_aggr_up)] <- 0
```

#### continue from this point**
```{r heatmap | modify this as it's only GO terms now, not clusters}
library(ComplexHeatmap)
library(circlize)
library(grid)
library(dplyr)
library(stringr)
library(GOSemSim)

#--------------------------------
# 0. Define vector of individual GO terms (character vector)
#--------------------------------
# Must match rownames of your matrix exactly
go_terms <- rownames(sig_mat_indiv_aggr_up)

#--------------------------------
# 1. Compute semantic similarity matrix
#--------------------------------
hsGO <- godata('org.Hs.eg.db', ont = "BP")

n <- length(go_terms)
sim_matrix <- matrix(NA, n, n)
rownames(sim_matrix) <- colnames(sim_matrix) <- go_terms

for (i in seq_len(n)) {
  for (j in seq_len(n)) {
    sim_matrix[i, j] <- mgoSim(go_terms[i], go_terms[j], semData = hsGO, measure = "Wang", combine = "BMA")
  }
}

#--------------------------------
# 2. Hierarchical clustering and reordering
#--------------------------------
hc <- hclust(as.dist(1 - sim_matrix), method = "average")
ordered_go_terms <- hc$labels[hc$order]

#--------------------------------
# 3. Reorder matrix by GO semantic similarity
#--------------------------------
sig_mat_indiv_aggr_up_ordered <- sig_mat_indiv_aggr_up[ordered_go_terms, , drop = FALSE]

```

```{r up signature heatmap}
#-------------------------------
# 1. Define tissue short names
#-------------------------------
tissue_map <- c(
  "blood_pmbc"                         = "PBMC",
  "blood_pbmc"                         = "PBMC",
  "blood_PBMC"                         = "PBMC",
  "blood_whole_blood"                  = "whole_blood",
  "blood_monocytes"                    = "monocyte",
  "blood_monocyte"                     = "monocyte",
  "blood_monocyte_derived_macrophages" = "mono_macro",
  "blood_monocyte_derived_macrophage"  = "mono_macro",
  "blood_macrophage"                   = "macro_blood",
  "PBMC_macrophage"                    = "PBMC_macro",
  "blood_dendritic_cells"              = "DC_blood",
  "blood_dcs"                          = "DC_blood",
  "blood_lymphatic_endothelial_cell"   = "endo_blood",
  "blood_THP-1"                        = "THP1_macro",
  "THP-1"                              = "THP1_macro",
  "blood_marcophages"                  = "macro_blood",  # assuming typo for "macrophages"
  "blood_blood"                        = "blood",
  "blood"                              = "blood",
  "lymphnode_lymphnode"                = "lymphnode",
  "BAL_bronchoalveolar_lavage"         = "BAL",
  "BALF_alveolar_macrophage"           = "alveolar_macro_BALF",
  "lung_ILC1"                          = "ILC1_lung",
  "lung_ILC2"                          = "ILC2_lung",
  "lung_ILC3neg"                       = "ILC3neg_lung",
  "lung_ILC3pos"                       = "ILC3pos_lung",
  "lung_NK"                            = "NK_lung",
  "lung_susp"                          = "lung_cells",
  "HEPG2_HepG2"                        = "HepG2_cells"
)

#---------------------------------------
# 2. Define tissue & technology colors
#---------------------------------------
tissue_colors <- c(
  # Blood-related (red/orange tones)
  "PBMC"                  = "#E41A1C",
  "whole_blood"           = "#B22222",
  "monocyte"              = "#FF4500",
  "mono_macro"            = "#FF6347",
  "macro_blood"           = "#FF7F50",
  "PBMC_macro"            = "#FF8C00",
  "DC_blood"              = "#CD5C5C",
  "endo_blood"            = "#FA8072",
  "blood"                 = "#DC143C",

  # Lung-related (blue/green tones)
  "alveolar_macro_BALF"   = "#009E73",
  "ILC1_lung"             = "#1F78B4",
  "ILC2_lung"             = "#33A02C",
  "ILC3neg_lung"          = "#66C2A5",
  "ILC3pos_lung"          = "#A6D854",
  "NK_lung"               = "#377EB8",
  "lung_cells"            = "#5CA8C8",
  "BAL"                   = "#41B6C4",

  # Cell lines (grey/purple tones)
  "THP1_macro"            = "#7F7F7F",  # grey
  "HepG2_cells"           = "#BC80BD",  # muted purple

  # Other tissues
  "lymphnode"             = "#FDB462"
)


tech_colors <- c(
  "RNASeq" = "#E69F00",
  "microarray" = "#56B4E9"
)

#---------------------------------------
# 3. Prepare metadata
#---------------------------------------
meta_df <- final_summary_df %>%
  filter(signature %in% colnames(sig_mat_indiv_aggr_up)) %>%
  mutate(
    tissue_short = recode(cell_tissue_type, !!!tissue_map),
    GSE_id_tissue_cell = ifelse(
      is.na(platform_id) | platform_id == "" | platform_id == "NA",
      str_c(study_id, tissue_short, sep = "_"),
      str_c(study_id, platform_id, tissue_short, sep = "_")
    )
  )
meta_df$GSE_id_tissue_cell[nrow(meta_df) - 1] <- "aggregated_microarray"
meta_df$GSE_id_tissue_cell[nrow(meta_df)]     <- "aggregated_rnaseq"

# Match column order of sig_mat
meta_df_sorted <- meta_df %>%
  right_join(tibble(signature = colnames(sig_mat_indiv_aggr_up)), by = "signature")


#---------------------------------------
# 4. Set rownames and transform matrix
#---------------------------------------
colnames(sig_mat_indiv_aggr_up_ordered) <- meta_df_sorted$GSE_id_tissue_cell
sig_mat_log <- -log10(sig_mat_indiv_aggr_up_ordered)
sig_mat_log[sig_mat_log > 20] <- 20  # cap extreme values

col_fun <- colorRamp2(
  c(0, 5, 10, 15),
  c("white", "lightgreen", "forestgreen", "darkgreen")
)

#---------------------------------------
# 5. Create top and bottom annotations
#---------------------------------------
ha_top <- HeatmapAnnotation(
  technology = meta_df_sorted$technology,
  col = list(technology = tech_colors),
  annotation_name_side = "left" 
)

ha_bottom <- HeatmapAnnotation(
  tissue_cell = meta_df_sorted$tissue_short,
  TB = meta_df_sorted$TB,
  origin_type = meta_df_sorted$origin_type,
  col = list(
    tissue_cell = tissue_colors,
    technology = tech_colors
  ),
  annotation_name_side = "left" 
)

#---------------------------------------
# 6. Plot heatmap and save
#---------------------------------------
pdf("/Users/kewalinsamart/Documents/GitHub/drugrep_tb/figures/up_stats_hv_indiv_aggr_rnaseq_marray_GOterms_technology.pdf", width = 40, height = 30)

heatmap_sig_up_go <- Heatmap(
  sig_mat_log,
  name = "GO term enrichment",
  col = col_fun,
  heatmap_legend_param = list(
    title = "-log10(q-value)",
    title_gp = gpar(fontsize = 15),
    labels_gp = gpar(fontsize = 16)
  ),
  column_title = "Individual upregulated \n microarray & RNASeq TB signatures",
  row_title = "Enriched GO biological processes",
  rect_gp = gpar(col = "grey"),
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  row_order = rownames(sig_mat_log),
  column_names_rot = 70,
  top_annotation = ha_top,
  bottom_annotation = ha_bottom,
  row_names_gp = gpar(fontsize = 16),
  column_names_gp = gpar(fontsize = 16),
  width = unit(42, "cm"),
  height = unit(25, "cm")
)

draw(heatmap_sig_up_go,
     heatmap_legend_side = "left", 
     annotation_legend_side = "left")

dev.off()
```
