```{r setup, include=FALSE}
library(ComplexHeatmap)
library(colorRamp2)
library(clusterProfiler)
library(DOSE)
library(org.Hs.eg.db)
library(readr)
library(here)
source(here("scripts/00_get_crossSigs_enrichedGO.R"))
library(gridExtra)
library(grid)
library(tibble)
library(tidyr)
library(tidyverse)
```

### Up individual signatures
```{r define indiv file paths}
marray_path_up <- here("data/v2/microarray_pathways/up")
# marray_path_dn <- here("data/v2/microarray_pathways/dn")
rnaseq_path_up <- here("data/v2/RNAseq_pathways/up")
# rnaseq_path_dn <- here("data/v2/RNAseq_pathways/dn")
```

```{r define accessory variables/paths}
pattern <- "GO_ORA_BGcorrected"
prefix_sub <- "GO_ORA_BGcorrected"
suffix_sub <- "up.tsv"
annotation_file='data/metadata/direct-annotations__Homo_sapiens__Entrez.tsv'
```

```{r microarray up pathway clusters}
marray_GO_mat_up = get_GO_generatio_matrix(marray_path_up, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

```{r RNAseq up pathway clusters}
rnaseq_GO_mat_up = get_GO_generatio_matrix(rnaseq_path_up, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

# combine pathways from both marray and rnaseq and perform clustering
```{r read in metadata tabel}
summary_df <- read.delim(here("data/metadata/202506_TB_signatures_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
new_row_aggr <- data.frame(
  study_id = c(NA,NA),
  platform_id = c(NA,NA),
  tb_status = c(NA,NA),
  time_point = c(NA,NA),
  tissue_cell_type = c(NA,NA),
  sample_origin = c(NA,NA),
  tissue_category = c(NA,NA),  
  series_id = c(NA,NA), 
  SIGNATURE_NAME = c("aggregated_microarray", "aggregated_RNAseq"),  
  EXPRMAT_PATH = c(NA,NA),    
  signature = c(1,1),
  up_genes_num = c(98,98),
  dn_genes_num = c(98,98),
  technology = c("microarray", "RNAseq")
)

final_summary_df = rbind(summary_df, new_row_aggr)
#write_tsv(final_summary_df, here("data/metadata/202506_all_TB_signatures_info.tsv"))
```


```{r}
# Assuming both data frames have Description as row names
# If it's a column instead, set it as rownames first

cols_to_keep_marray <- intersect(colnames(marray_GO_mat_up), c("Description", summary_df$SIGNATURE_NAME, "up_aggregated_microarray_DE"))
df1 <- marray_GO_mat_up[, cols_to_keep_marray]
colnames(df1) <- gsub("^up_", "", colnames(df1))
colnames(df1) <- gsub("_DE", "", colnames(df1))

cols_to_keep_rnaseq <- intersect(colnames(rnaseq_GO_mat_up), c("Description", summary_df$SIGNATURE_NAME, "up_aggregated_RNAseq_DE", "up_aggregated_RNAseq_DE_blood"))
df2 <- rnaseq_GO_mat_up[, cols_to_keep_rnaseq]
colnames(df2) <- gsub("^up_", "", colnames(df2))
colnames(df2) <- gsub("_DE", "", colnames(df2))

# Reshape from wide to long
library(tidyr)
long1 <- pivot_longer(df1, -Description, names_to = "Signature", values_to = "Value")
long2 <- pivot_longer(df2, -Description, names_to = "Signature", values_to = "Value")

# Combine long formats and sum values where matching
library(dplyr)
combined_long <- bind_rows(long1, long2) %>%
  group_by(Description, Signature) %>%
  summarise(
  Value = if (all(is.na(Value))) NA_real_ else max(Value, na.rm = TRUE),
  .groups = "drop"
)

# Reshape back to wide format
final_df_up <- pivot_wider(combined_long, names_from = Signature, values_from = Value)
colnames(final_df_up) <- gsub("\\.", "-", colnames(final_df_up))

# Identify columns with "aggregated" in their names
agg_cols <- grep("aggregated", names(final_df_up), value = TRUE)

# Identify columns that do not contain "aggregated"
non_agg_cols <- setdiff(names(final_df_up), agg_cols)

# Reorder the dataframe
final_df_up <- final_df_up[, c(non_agg_cols, agg_cols)]
# Identify columns
desc_col <- grep("Description", names(final_df_up), value = TRUE)
gpl_cols <- grep("GPL", names(final_df_up), value = TRUE)
rnaseq_col <- grep("RNAseq", names(final_df_up), value = TRUE)
other_cols <- setdiff(names(final_df_up), c(gpl_cols, rnaseq_col))

# Reorder dataframe
final_df_up <- final_df_up[, c(desc_col, gpl_cols, other_cols, rnaseq_col)]
final_df_up <- final_df_up[, !duplicated(colnames(final_df_up))]
final_df_up <- final_df_up[, !grepl("HIV", colnames(final_df_up))]
write_tsv(final_df_up,here("figures/marray_rnaseq_up_pathways_suppl.tsv"))
```

### Dn individual signatures
```{r define indiv file paths}
#marray_path_up <- here("data/v2/microarray_pathways/up")
marray_path_dn <- here("data/v2/microarray_pathways/dn")
#rnaseq_path_up <- here("data/v2/RNAseq_pathways/up")
rnaseq_path_dn <- here("data/v2/RNAseq_pathways/dn")
```

```{r define accessory variables/paths}
pattern <- "GO_ORA_BGcorrected"
prefix_sub <- "GO_ORA_BGcorrected"
suffix_sub <- "dn.tsv"
annotation_file='data/metadata/direct-annotations__Homo_sapiens__Entrez.tsv'
```

```{r microarray up pathway clusters}
marray_GO_mat_dn = get_GO_generatio_matrix(marray_path_dn, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

```{r RNAseq up pathway clusters}
rnaseq_GO_mat_dn = get_GO_generatio_matrix(rnaseq_path_dn, pattern, prefix_sub, suffix_sub)
GO_annotation = get_GO_annotation(here(annotation_file))
```

# combine pathways from both marray and rnaseq and perform clustering
```{r read in metadata tabel}
summary_df <- read.delim(here("data/metadata/202506_TB_signatures_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
new_row_aggr <- data.frame(
  study_id = c(NA,NA),
  platform_id = c(NA,NA),
  tb_status = c(NA,NA),
  time_point = c(NA,NA),
  tissue_cell_type = c(NA,NA),
  sample_origin = c(NA,NA),
  tissue_category = c(NA,NA),  
  series_id = c(NA,NA), 
  SIGNATURE_NAME = c("aggregated_microarray", "aggregated_RNAseq"),  
  EXPRMAT_PATH = c(NA,NA),    
  signature = c(1,1),
  up_genes_num = c(98,98),
  dn_genes_num = c(98,98),
  technology = c("microarray", "RNAseq")
)

final_summary_df = rbind(summary_df, new_row_aggr)
#write_tsv(final_summary_df, here("data/metadata/202506_all_TB_signatures_info.tsv"))
```


```{r}
# Assuming both data frames have Description as row names
# If it's a column instead, set it as rownames first

cols_to_keep_marray <- intersect(colnames(marray_GO_mat_dn), c("Description", summary_df$SIGNATURE_NAME, "dn_aggregated_microarray_DE"))
df1 <- marray_GO_mat_dn[, cols_to_keep_marray]
colnames(df1) <- gsub("^dn_", "", colnames(df1))
colnames(df1) <- gsub("_DE", "", colnames(df1))

cols_to_keep_rnaseq <- intersect(colnames(rnaseq_GO_mat_dn), c("Description", summary_df$SIGNATURE_NAME, "dn_aggregated_RNAseq_DE", "dn_aggregated_RNAseq_DE_blood"))
df2 <- rnaseq_GO_mat_dn[, cols_to_keep_rnaseq]
colnames(df2) <- gsub("^dn_", "", colnames(df2))
colnames(df2) <- gsub("_DE", "", colnames(df2))

# Reshape from wide to long
library(tidyr)
long1 <- pivot_longer(df1, -Description, names_to = "Signature", values_to = "Value")
long2 <- pivot_longer(df2, -Description, names_to = "Signature", values_to = "Value")

# Combine long formats and sum values where matching
library(dplyr)
combined_long <- bind_rows(long1, long2) %>%
  group_by(Description, Signature) %>%
  summarise(
  Value = if (all(is.na(Value))) NA_real_ else max(Value, na.rm = TRUE),
  .groups = "drop"
)

# Reshape back to wide format
final_df_dn <- pivot_wider(combined_long, names_from = Signature, values_from = Value)
colnames(final_df_dn) <- gsub("\\.", "-", colnames(final_df_dn))

# Identify columns with "aggregated" in their names
agg_cols <- grep("aggregated", names(final_df_dn), value = TRUE)

# Identify columns that do not contain "aggregated"
non_agg_cols <- setdiff(names(final_df_dn), agg_cols)

# Reorder the dataframe
final_df_dn <- final_df_dn[, c(non_agg_cols, agg_cols)]
# Identify columns
desc_col <- grep("Description", names(final_df_dn), value = TRUE)
gpl_cols <- grep("GPL", names(final_df_dn), value = TRUE)
rnaseq_col <- grep("RNAseq", names(final_df_dn), value = TRUE)
other_cols <- setdiff(names(final_df_dn), c(gpl_cols, rnaseq_col))

# Reorder dataframe
final_df_dn <- final_df_dn[, c(desc_col, gpl_cols, other_cols, rnaseq_col)]
final_df_dn <- final_df_dn[, !duplicated(colnames(final_df_dn))]
final_df_dn <- final_df_dn[, !grepl("HIV", colnames(final_df_dn))]
write_tsv(final_df_dn,here("figures/marray_rnaseq_dn_pathways_suppl.tsv"))
```