```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Documents/GitHub/drugrep_tb/")
library(ComplexHeatmap)
library(colorRamp2)
#library(ReactomePA) # can't install this
library(clusterProfiler)
library(DOSE)
library(readr)
source("~/Documents/GitHub/drugrep_tb/scripts/00_get_crossSigs_enrichedGO.R")
library(gridExtra)
library(grid)
library(tibble)
library(tidyr)
library(here)
```

```{r load data}
summary_df <- read.delim(here("data/v2/tableS1/202506_all_TB_signatures_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
summary_df 
```

```{r read in microarray and RNAseq}
microarray_df <- read.delim(here("data/v2/tableS1/microarray_TB_signature_run_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
rnaseq_df <- read.delim(here("data/v2/tableS1/RNAseq_TB_signature_run_info.tsv"), sep = "\t", stringsAsFactors = FALSE)
combined_df <- rbind(microarray_df, rnaseq_df)
combined_df
```
```{r}
library(dplyr)
all_info <- left_join(summary_df, combined_df, by = "SIGNATURE_NAME")
all_info
```

```{r gt table}
library(gt)
library(readr)
library(dplyr)

# Reorder 'technology' to prioritize 'microarray' first
all_info$technology <- factor(all_info$technology, levels = c("microarray", setdiff(unique(all_info$technology), "microarray")))

all_info = all_info[all_info$signature.x == 1,]

# Create the table
my_gt_table <- all_info %>%
  dplyr::select(SIGNATURE_NAME, study_id, platform_id, tb_status, sample_origin, tissue_category, tissue_cell_type, technology, up_genes_num.x, dn_genes_num.x) %>%
  arrange(technology) %>%
  gt(groupname_col = "technology") %>%
  tab_header(
    title = "TB Signature Metadata",
    subtitle = "Grouped by Technology"
  ) %>%
  cols_label(
    SIGNATURE_NAME = "Signature",
    study_id = "Study",
    platform_id = "Platform",
    tb_status = "TB Status",
    tissue_category = "Tissue Origin",
    sample_origin = "Origin Type",
    tissue_cell_type = "Cell/Tissue Type",
    technology = "Technology",
    up_genes_num.x = "Up Genes",
    dn_genes_num.x = "Down Genes"
  ) %>%
  fmt_missing(
    columns = everything(),
    missing_text = "-"
  ) %>%
  tab_options(
    table.font.size = "small",
    heading.title.font.size = 16,
    heading.subtitle.font.size = 12
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightblue")
    ),
    locations = cells_body(
      columns = vars(technology),
      rows = technology == "microarray"
    )
  ) %>%
  tab_style(
    style = list(
      cell_fill(color = "lightgreen")
    ),
    locations = cells_body(
      columns = vars(technology),
      rows = technology == "RNAseq"
    )
  )

# Save the table as HTML
gtsave(my_gt_table, here("figures/signature_summary_table.html"))

```

```{r check output}
my_gt_table
```
