```{r Figure S5 function}
library(readr)
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(matrixStats)
library(data.table)

# function to process a file and return a tidy dataframe for plotting
process_file <- function(filepath, direction_label) {
  df <- as_tibble(fread(here(filepath)))
  
  # define microarray and RNAseq individual signature columns
  microarray_cols <- colnames(df)[2:7]
  rnaseq_cols <- setdiff(colnames(df)[2:(ncol(df) - 2)], microarray_cols)

  # compute median of individual signatures for each Technology
  median_micro <- rowMedians(as.matrix(df[, microarray_cols]), na.rm = TRUE)
  median_rna <- rowMedians(as.matrix(df[, rnaseq_cols]), na.rm = TRUE)

  # compute squared deviation from the median
  sq_dev_micro <- (df$aggregated_microarray - median_micro)^2 / length(microarray_cols)
  sq_dev_rna <- (df$aggregated_RNAseq - median_rna)^2 / length(rnaseq_cols)
  
  # combine into tidy data frame with direction label
  tibble(
    Pathway = df$Description,
    Microarray = sq_dev_micro,
    RNAseq = sq_dev_rna,
    Direction = direction_label
  ) %>%
    pivot_longer(cols = c(Microarray, RNAseq), names_to = "Technology", values_to = "SquaredDeviation")
}
```

```{r Figure S5 plot}
# process both up- and dn-regulated pathways files
plot_df_up <- process_file("figures/figureS4/figureS4a/marray_rnaseq_asinh_up_pathways.tsv", "Upregulated")
plot_df_dn <- process_file("figures/figureS4/figureS4b/marray_rnaseq_asinh_dn_pathways.tsv", "Downregulated")

# combine both into one dataframe
combined_plot_df <- bind_rows(plot_df_up, plot_df_dn) %>%
  mutate(Direction = factor(Direction, levels = c("Upregulated", "Downregulated")))

# compute medians for label annotations
med_labels <- combined_plot_df %>%
  group_by(Direction, Technology) %>%
  summarise(SquaredDeviation = median(SquaredDeviation, na.rm = TRUE), .groups = "drop")

# plot
ggplot(combined_plot_df, aes(x = Technology, y = SquaredDeviation, fill = Technology)) +
  #geom_violin(trim = FALSE, alpha = 0.4) +
  geom_boxplot() +
  #coord_trans(y = "log10") +
  #scale_y_log10(labels = scales::comma_format()) +
  scale_fill_brewer(palette = "Set2") +
  geom_text(data = med_labels,
            aes(x = Technology, y = SquaredDeviation, label = format(SquaredDeviation, scientific = TRUE, digits = 4)
),
            vjust = -1,
            hjust = -2,
            size = 5,
            color = "black",
            inherit.aes = FALSE) +
  labs(
    title = "Squared deviation of aggregated signatures from median of individual signatures",
    y = "Squared deviation",
    x = "Technology"
  ) +
  facet_wrap(~Direction) +
  theme_minimal(base_size = 20) +   
  theme(
    legend.position = "none",
    plot.title = element_text(size = 24, hjust = 0.5), 
    axis.title = element_text(size = 22),
    axis.text = element_text(size = 18),
    strip.text = element_text(size = 20)  
  ) +
  coord_cartesian(clip = "off")

```

```{r figure S5 data}
library(dplyr)

# choose how many lowest SD pathways you want to plot per group
top_n <- 10

lowest_sd_paths <- combined_plot_df %>%
  group_by(Direction, Technology) %>%
  slice_min(order_by = SquaredDeviation, n = top_n, with_ties = FALSE) %>%
  ungroup()

```

```{r}
lowest_sd_paths_all <- combined_plot_df %>%
  group_by(Direction, Technology) %>%
  slice_min(order_by = SquaredDeviation, with_ties = TRUE) %>%
  ungroup()


print(dim(combined_plot_df))
print(dim(lowest_sd_paths_all))
print(dim(lowest_sd_paths_all)[1]/dim(combined_plot_df)[1]*100) # percentage of pathways with zero squared deviation
```


```{r figure S5 data}
# choose how many highest SD pathways you want to plot per group
top_n <- 10

highest_sd_paths <- combined_plot_df %>%
  group_by(Direction, Technology) %>%
  slice_max(order_by = SquaredDeviation, n = top_n, with_ties = FALSE) %>%
  ungroup()

```

```{r figure S5; plotting}
library(ggplot2)

pdf(here("figures/figureS5/FigureS5_squared_deviation_less_captured.pdf"),
    width = 16, height = 8)  

ggplot(highest_sd_paths, aes(x = reorder(Pathway, SquaredDeviation), y = SquaredDeviation, fill = Technology)) +
  scale_fill_brewer(palette = "Set2") +
  geom_col(position = position_dodge(width = 0.8)) +
  facet_wrap(~ Direction, scales = "free_x") +
  coord_flip() +
  labs(
    title = "Pathways less conserved in aggregated sigatures \n (highest squared deviation)",
    x = "Pathway",
    y = "Squared deviation"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    plot.title = element_text(size = 20, hjust = 0.5), 
    axis.text = element_text(size = 11),
    axis.title = element_text(size = 18),
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(size = 15)
  )

dev.off()
```