```{r}
library(ggplot2)
library(here)
library(readr)
library(tidyverse)
library(dplyr)
```

```{r define moa_novel}
# moa_novel
moa_novel = read_tsv(here("figures/figureS8/novel_moa_counts_final_predictions.tsv"))
```

```{r plot moa novelty freq}
pdf(here("figures/figureS8/FigureS8_moa_frequency.pdf"), width = 20, height = 15)

ggplot(moa_novel, aes(x = reorder(moa, -n_drugs), y = n_drugs, fill = factor(novel))) +
  geom_bar(stat = "identity") +
  labs(
    title = "Frequency of MOAs associated with our 64 high confidence candidates",
    x = "Mechanism of Action (MOA)",
    y = "Count",
    fill = "Novelty"
  ) +
  scale_fill_manual(
    values = c("0" = "steelblue", "1" = "orange"),
    labels = c("0" = "Known", "1" = "Novel")
  ) +
  theme_bw(base_size = 20) +
  theme(
    plot.title = element_text(size = 28, hjust = 0.5),
    axis.title.x = element_text(size = 22, margin = margin(t = 15)),
    axis.title.y = element_text(size = 22, margin = margin(r = 15)),
    axis.text.x = element_text(size = 14, angle = 60, hjust = 1, vjust = 1),
    axis.text.y = element_text(size = 16),
    panel.grid.major.x = element_blank(),
    plot.margin = margin(20, 20, 20, 20)
  )



dev.off()

```