# Finalizing drug prediction across technologies and methods

```{r}
library(here)
library(readr)
```

```{r read in drug lists}
RAresult_indivSig_TB_microarray <- readRDS(here("results/microarray/04_rank_aggregation/RAresult_indivSig_TB_microarray.rds"))
print(paste0("Number of microarray individual signatures' drug candidates: ", length(RAresult_indivSig_TB_microarray)))

RAresult_neg_left_0.9_aggrSig_TB_microarray <- readRDS(here("results/microarray/04_rank_aggregation/RAresult_neg_left_0.9_aggrSig_TB_microarray.rds"))
print(paste0("Number of microarray aggregated signatures' drug candidates: ", length(RAresult_neg_left_0.9_aggrSig_TB_microarray)))

RAresult_indivSig_TB_RNAseq <- readRDS(here("results/RNAseq/04_rank_aggregation/RAresult_indivSig_TB_RNAseq.rds"))
print(paste0("Number of RNAseq individual signatures' drug candidates: ", length(RAresult_indivSig_TB_RNAseq)))

RAresult_neg_left_0.9_aggrSig_TB_RNAseq <- readRDS(here("results/RNAseq/04_rank_aggregation/RAresult_neg_left_0.9_aggrSig_TB_RNAseq.rds"))
print(paste0("Number of RNAseq aggregated signatures' drug candidates: ", length(RAresult_neg_left_0.9_aggrSig_TB_RNAseq)))
```

#### How many drugs derived from individual and aggregated signatures are shared across technologies?

```{r}
print(paste0("Overalaps between microarray and RNAseq of individual signatures's predictions: ", length(intersect(RAresult_indivSig_TB_microarray, RAresult_indivSig_TB_RNAseq))))

print(paste0("Overalaps between microarray and RNAseq of aggregated signatures's predictions: ",length(intersect(RAresult_neg_left_0.9_aggrSig_TB_microarray, RAresult_neg_left_0.9_aggrSig_TB_RNAseq))))
```

```{r}
print(length(union(RAresult_indivSig_TB_microarray, RAresult_indivSig_TB_RNAseq)))
print(length(union(RAresult_neg_left_0.9_aggrSig_TB_microarray, RAresult_neg_left_0.9_aggrSig_TB_RNAseq)))

print(paste0("Number of final drug candidates --- union of two technologies and intersection across the two signature types: ", length(intersect(union(RAresult_indivSig_TB_microarray, RAresult_indivSig_TB_RNAseq),union(RAresult_neg_left_0.9_aggrSig_TB_microarray, RAresult_neg_left_0.9_aggrSig_TB_RNAseq)))))
```

```{r v1 vs. v2}
v1_drug_candiadtes = read_tsv(here("results/v1_intersect_RAresult_drugs.tsv"))$intersect_RAresult_drugs
v2_drug_candidates = intersect(union(RAresult_indivSig_TB_microarray, RAresult_indivSig_TB_RNAseq),union(RAresult_neg_left_0.9_aggrSig_TB_microarray, RAresult_neg_left_0.9_aggrSig_TB_RNAseq))

print("Shared drugs from v1 and v2 final predictions: ")
intersect(v1_drug_candiadtes, v2_drug_candidates)
```
